export enum ErrorCode {
  // Auth / Account
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_USER_TYPE = "INVALID_USER_TYPE",

  // Product
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_NOT_FOUND_OR_UNAVAILABLE = "PRODUCT_NOT_FOUND_OR_UNAVAILABLE",

  // Cart
  CART_EMPTY = "CART_EMPTY",
  CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND",
  CART_ITEMS_UNAVAILABLE = "CART_ITEMS_UNAVAILABLE",

  // Favorites
  PRODUCT_ALREADY_FAVORITED = "PRODUCT_ALREADY_FAVORITED",

  // Authorization
  UNAUTHORIZED = "UNAUTHORIZED",

  // Payment
  PAYMENT_FAILED = "PAYMENT_FAILED"
}
